---
- hosts: localhost
  # run this task in the host
  connection: local
  tasks:
    - name: create containers
      # get all host names from inventory
      loop: "{{ groups['all'] }}"
      # use lxd_container module from ansible to create containers
      community.general.lxd_container:
        # container name is the hostname
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: ubuntu/focal/amd64
        config:
          # nomad clients need some privileges to be able to run docker containers
          security.nesting: "{{ 'true' if item in groups['nomad_clients'] else 'false' }}"
          security.privileged: "{{ 'true' if item in groups['nomad_clients'] else 'false' }}"
        # uncomment if you installed lxd using snap
        url: unix:/var/snap/lxd/common/lxd/unix.socket

    # ensure cache directory exists
    - name: create cache directory
      file:
        path: cache
        state: directory
  
    # - name: fetch cni plugins
    #   get_url:
    #     url: "{{ cni_plugins_url }}"
    #     dest: cache/cni-plugins.tgz

    # - name: create plugins directory
    #   file:
    #     path: cache/cni-plugins
    #     state: directory

    # - name: extract cni plugins
    #   command: tar -xzf cni-plugins.tgz -C cni-plugins/
    #   args:
    #     chdir: cache

- hosts: consul_servers
  roles:
    - consul_server

- hosts: nomad_servers
  roles:
    - consul_client
    - nomad_server

- hosts: nomad_clients
  roles:
    - consul_client
    - nomad_client

- hosts: proxy
  roles:
    - consul_client
    - proxy
