---
- hosts: localhost
  # run this task in the host
  connection: local
  tasks:
    - name: create containers
      # get all host names from inventory
      loop: "{{ groups['all'] }}"
      # use lxd_container module from ansible to create containers
      lxd_container:
        # container name is the hostname
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: ubuntu/focal/amd64
        config:
          # nomad clients need some privileges to be able to run docker containers
          security.nesting: "{{ 'true' if item in groups['nomad_clients'] else 'false' }}"
          security.privileged: "{{ 'true' if item in groups['nomad_clients'] else 'false' }}"
        devices:
          # configure network interface
          eth0:
            type: nic
            nictype: bridged
            parent: lxdbr0
            # get ip address from inventory
            ipv4.address: "{{ hostvars[item].ip_address }}"
        # uncomment if you installed lxd using snap
        url: unix:/var/snap/lxd/common/lxd/unix.socket

    # ensure cache directory exists
    - name: create cache directory
      file:
        path: cache
        state: directory

    - name: fetch applications
      unarchive:
        src: "{{ item.url }}"
        dest: cache
        creates: "cache/{{ item.file }}"
        remote_src: yes
      loop:
        - url: "{{ consul_url }}"
          file: consul
        - url: "{{ nomad_url }}"
          file: nomad
  
    - name: fetch cni plugins
      get_url:
        url: "{{ cni_plugins_url }}"
        dest: cache/cni-plugins.tgz

    - name: create plugins directory
      file:
        path: cache/cni-plugins
        state: directory

    - name: extract cni plugins
      command: tar -xzf cni-plugins.tgz -C cni-plugins/
      args:
        chdir: cache

    - name: fecth traefik
      get_url:
        url: "{{ traefik_url }}"
        dest: cache/traefik.tar.gz

    - name: extract traefik
      command: tar -xzf traefik.tar.gz traefik
      args:
        chdir: cache
        creates: traefik

- hosts: consul_servers
  roles:
    - consul_server

- hosts: nomad_servers
  roles:
    - consul_client
    - nomad_server

- hosts: nomad_clients
  roles:
    - consul_client
    - nomad_client

- hosts: proxy
  roles:
    - consul_client
    - proxy
