---
- name: install traefik
  unarchive:
    src: "{{ traefik_url }}"
    remote_src: yes
    dest: /usr/local/bin/
    mode: 0755
    extra_opts:
      - traefik

- name: create traefik service
  copy:
    src: traefik.service
    dest: /etc/systemd/system/

- name: create traefik config directory
  file:
    path: /etc/traefik
    state: directory

- name: copy traefik config
  template:
    src: traefik.toml.j2
    dest: /etc/traefik/traefik.toml

- name: create traefik file provider directory
  file:
    path: /etc/traefik/conf
    state: directory

- name: copy traefik file provider config
  template:
    src: nomad.toml.j2
    dest: /etc/traefik/conf/nomad.toml

- name: start traefik
  service:
    name: traefik
    state: restarted
    enabled: yes
