---
- import_role:
    name: nomad_service

- name: install gpg
  apt:
    name: gpg
    state: present

- name: add envoy apt key
  apt_key:
    url: "{{ envoy_gpg_url }}"
    state: present

- name: add envoy apt repository
  apt_repository:
    repo: "{{ envoy_repo }}"
    state: present

- name: add docker apt key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: add docker apt repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: update apt cache
  apt:
    update_cache: yes

- name: install envoy
  apt:
    name: getenvoy-envoy
    state: present

- name: install docker
  apt:
    name: "{{ item.package }}"
    state: present
  loop:
    - package: docker-ce
    - package: containerd.io 

- name: install openjdk
  apt:
    name: openjdk-11-jdk-headless
    state: present

- name: allow bridge network
  shell: "echo 1 > {{ item.dest }}"
  loop:
    - dest: /proc/sys/net/bridge/bridge-nf-call-arptables
    - dest: /proc/sys/net/bridge/bridge-nf-call-ip6tables
    - dest: /proc/sys/net/bridge/bridge-nf-call-iptables

- name: persist bridge network permission
  copy:
    src: bridge-network.conf
    dest: /etc/sysctl.d/bridge-network.conf

- name: copy cni plugins
  copy:
    src: cache/cni-plugins/
    dest: /opt/cni/bin/
    mode: 755

- name: start docker service
  service:
    name: docker
    state: started

- name: copy nomad config
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: start nomad
  service:
    name: nomad
    state: restarted
    enabled: yes
