---
- import_role:
    name: hashicorp_apt

- name: install consul
  apt:
    name: consul
    state: present

- name: create consul directory
  file:
    path: /var/consul
    state: directory
    owner: consul
    group: consul